name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

# Cancel existing runs for the same pull request (but give main branch builds unique groups)
concurrency:
  group: >-
    ${{
      github.event_name == 'pull_request'
        && format('{0}-{1}', github.workflow, github.event.pull_request.number)
        || format('{0}-{1}', github.workflow, github.run_id)
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  actions: read  # For artifact uploads

env:
  CARGO_TERM_COLOR: always

jobs:
  # Fast checks that run in parallel
  fast-checks:
    name: Fast Checks
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        check: [format, clippy, autofixers]
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-ubuntu-${{ hashFiles('**/Cargo.lock') }}

      # Conditional steps based on the check type
      - name: Check formatting
        if: matrix.check == 'format'
        run: cargo fmt --all -- --check

      - name: Run clippy
        if: matrix.check == 'clippy'
        run: cargo clippy --workspace -- -D warnings

      - name: Add lint summary
        if: matrix.check == 'clippy'
        run: |
          {
            echo "## Fast Checks (clippy)"
            echo
            echo "- ✅ \`cargo clippy --workspace -- -D warnings\`"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Run autofixers
        if: matrix.check == 'autofixers'
        run: make fmt

      - name: Ensure autofixers produced no changes
        if: matrix.check == 'autofixers'
        run: |
          if ! git diff --quiet --exit-code; then
            echo "Running \`make fmt\` generated changes."
            git status --short
            git diff
            exit 1
          fi

      - name: Add autofix summary
        if: matrix.check == 'autofixers'
        run: |
          {
            echo "## Fast Checks (autofixers)"
            echo
            echo "- ✅ \`make fmt\` produced no changes"
          } >> "$GITHUB_STEP_SUMMARY"

  # Tests can run in parallel with the fast-checks
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Build
        run: cargo build --workspace
      - name: Run tests
        run: cargo nextest run --workspace
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: confluence-dl-${{ matrix.os }}
          path: target/debug/confluence-dl
      - name: Add test summary
        if: success()
        run: |
          {
            echo "## Tests (${{ matrix.os }})"
            echo
            echo "- ✅ \`cargo nextest run --workspace\`"
          } >> "$GITHUB_STEP_SUMMARY"
